name: GitHub Actions Demo
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: docker build -f ./Dockerfile -t nginx-test .
      - run: docker tag nginx-test registry.xilin.icu/nginx-test
      - run: docker push registry.xilin.icu/nginx-test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
      - run: echo ${{ secrets.SERVER_IP }}
      - with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_PRIV_KEY }}
          script: docker pull registry.xilin.icu/nginx-test && docker run -p 8083:80 -rm -d registry.xilin.icu/nginx-test
