name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: git clone git@github.com:Kobe-G/todolist.git
      - run: cd todolist
      - run: docker build -f ./Dockerfile -t nginx-test .
      - run: docker tag nginx-test registry.xilin.icu/nginx-test
      - run: docker push registry.xilin.icu/nginx-test
